### ISSUE TITLE
Wonderful! Do you have a plan to support lower versions of Delphi?

### ISSUE THREAD

**Issue by edwinyzh** [renancostab/mockeverything#1]
I tried to compile under XE4 but failed, if you don't mind - do you have a plan to support lower versions of Delphi?

**Comment by renancostab** [comment]
Yes, I have plan to port it for lower versions. I'm working in a version
for Lazarus, but due some Rtti limitations it'll be probably a new project
and hope this version will be compatible with the lower versions of Delphi
(I guess Delphi XE and above).

Em qui, 28 de fev de 2019 às 01:10, Edwin Yip <notifications@github.com>
escreveu:

**Comment by renancostab** [comment]
The code was adapted for lower versions, and tested under Delphi XE, it's suppose to work in any versions Delphi XE and above.

**Comment by edwinyzh** [comment]
Compiled and run under XE4, thanks!
